USE [HCONCORDIA]
GO

/****** Object:  View [dbo].[VIQ_APIMEDICOS]    Script Date: 24/8/2023 22:04:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


 CREATE VIEW [dbo].[VIQ_APIMEDICOS]
 AS 
  SELECT 
            ISNULL(MED_NOMBRE, ' ') AS "NOMBRE PROFESIONAL",
            (SELECT ESP_NOMBRE FROM TMESPECIALIDADES WHERE MED_ESPECIALIDAD_1 = ESP_COD) AS "NOMBRE ESPECIALIDAD",
            CAST (TME2_FCH AS varchar) AS FECHA,
            CAST(TME2_HH AS VARCHAR) + ':' + CAST(TME2_MM AS VARCHAR) AS "HORA1",
            ISNULL(TME2_COD, '') AS "CODIGO CLIENTE",
            ISNULL((SELECT TOP 1 KC_NOM FROM TKCLIENTES WHERE TME2_ZONA = KC_ZONA AND TME2_COD = KC_COD), '') AS "NOMBRE CLIENTE",
            TME2_ACTIVIDAD AS ACTIVIDAD
        FROM TMTURNOSMEDICOSDETALLE
        LEFT JOIN TMMEDICOS ON (TME2_CODM = MED_COD)
        WHERE  TME2_ACTIVIDAD = 90

GO

