USE [HCONCORDIA]
GO

/****** Object:  View [dbo].[VIQ_APICITAS]    Script Date: 24/8/2023 22:06:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




 CREATE VIEW [dbo].[VIQ_APICITAS]
 AS 
 SELECT   ISNULL(KC_NOM,'')  "Nombre",  ISNULL(ENT_NOMBRE,'')
"Entidad",CAST (KC_COD AS bigint)AS ID  FROM TKCLIENTES  LEFT JOIN TMUSUARIOSFACTURACION 
ON KC_COD = KC2_COD  LEFT JOIN TMENTIDADES ON KC2_EPS_POS = ENT_COD     
WHERE KC_ZONA= '99' 


GO

